# Generated by Django 4.2.27 on 2026-01-16 13:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveQuizState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_ability', models.FloatField(default=0.0)),
                ('ability_variance', models.FloatField(default=1.0)),
                ('questions_pool', models.JSONField(default=list)),
                ('asked_questions', models.JSONField(default=list)),
                ('is_converged', models.BooleanField(default=False)),
                ('convergence_threshold', models.FloatField(default=0.1)),
                ('ability_history', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
            ],
            options={
                'db_table': 'adaptive_quiz_states',
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('topic_breakdown', models.JSONField(default=dict)),
                ('error_analysis', models.JSONField(default=dict)),
                ('comparison_to_peers', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('docx_url', models.URLField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'assessment_reports',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq_single', 'Multiple Choice (Single)'), ('mcq_multi', 'Multiple Choice (Multiple)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer/Essay'), ('code', 'Code Writing'), ('code_output', 'Code Output Prediction'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering/Sequence'), ('diagram_label', 'Diagram Labeling')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_html', models.TextField(blank=True)),
                ('question_media', models.URLField(blank=True, null=True)),
                ('code_template', models.TextField(blank=True)),
                ('programming_language', models.CharField(blank=True, max_length=50, null=True)),
                ('test_cases', models.JSONField(default=list)),
                ('diagram_url', models.URLField(blank=True, null=True)),
                ('label_positions', models.JSONField(default=list)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.JSONField()),
                ('answer_explanation', models.TextField(blank=True)),
                ('hints', models.JSONField(default=list)),
                ('points', models.IntegerField(default=1)),
                ('partial_credit', models.BooleanField(default=False)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('attempts_count', models.IntegerField(default=0)),
                ('correct_rate', models.FloatField(default=0.0)),
                ('avg_time_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_answer', models.JSONField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('partial_score', models.FloatField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=50, null=True)),
                ('misconception_detected', models.TextField(blank=True, null=True)),
                ('hints_viewed', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_reported', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_responses',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quiz_type', models.CharField(choices=[('practice', 'Practice Quiz'), ('assessment', 'Assessment'), ('exam', 'Final Exam'), ('diagnostic', 'Diagnostic Test'), ('adaptive', 'Adaptive Quiz')], max_length=20)),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('passing_score', models.FloatField(default=0.7)),
                ('max_attempts', models.IntegerField(default=3)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('is_adaptive', models.BooleanField(default=False)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('max_points', models.IntegerField(default=0)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('hints_used', models.JSONField(default=dict)),
                ('cognitive_metrics', models.JSONField(default=dict)),
                ('difficulty_progression', models.JSONField(default=list)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
