# Generated by Django 4.2.27 on 2026-01-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.quizattempt'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='assessments.quizattempt'),
        ),
        migrations.AddField(
            model_name='adaptivequizstate',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_state', to='assessments.quizattempt'),
        ),
        migrations.AddField(
            model_name='adaptivequizstate',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
