# Generated by Django 4.2.27 on 2026-01-16 13:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Rich Text'), ('markdown', 'Markdown'), ('code', 'Code Block'), ('image', 'Image'), ('diagram', 'Diagram'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('interactive', 'Interactive Widget'), ('quiz', 'Embedded Quiz'), ('project', 'Project Template')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('content_data', models.JSONField(default=dict)),
                ('raw_content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=50, null=True)),
                ('is_executable', models.BooleanField(default=False)),
                ('alt_text', models.TextField(blank=True)),
                ('diagram_type', models.CharField(blank=True, max_length=50, null=True)),
                ('labeled_components', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('keyframes', models.JSONField(default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_metadata', models.JSONField(default=dict)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('presentation_style', models.CharField(choices=[('detailed', 'Detailed Explanation'), ('concise', 'Concise Summary'), ('example_heavy', 'Example Heavy'), ('visual', 'Visual Focus'), ('interactive', 'Interactive')], default='detailed', max_length=20)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('content_data', models.JSONField()),
                ('raw_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('traffic_percentage', models.FloatField(default=0.0)),
                ('views', models.IntegerField(default=0)),
                ('avg_time_spent', models.DurationField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('ai_ml', 'AI/Machine Learning'), ('data_science', 'Data Science'), ('fullstack', 'Full-Stack Development'), ('devops', 'DevOps & Cloud'), ('hybrid', 'Hybrid Programming'), ('fundamentals', 'Programming Fundamentals')], max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('preview_video', models.URLField(blank=True, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=36000))),
                ('total_modules', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('learning_objectives', models.JSONField(default=list)),
                ('skills_gained', models.JSONField(default=list)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('total_topics', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('content_type', models.CharField(choices=[('theory', 'Theory/Concept'), ('practical', 'Practical/Hands-on'), ('project', 'Project'), ('review', 'Review'), ('assessment', 'Assessment')], max_length=20)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('concept_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('related_concepts', models.JSONField(default=list)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.module')),
                ('prerequisite_topics', models.ManyToManyField(blank=True, related_name='dependent_topics', to='courses.topic')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('completed_topics', models.ManyToManyField(blank=True, to='courses.topic')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('current_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='courses.topic')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
    ]
