# Generated by Django 4.2.27 on 2026-01-16 13:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_active_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_session_duration', models.DurationField(blank=True, null=True)),
                ('content_interaction_rate', models.FloatField(default=0.0)),
                ('quiz_completion_rate', models.FloatField(default=0.0)),
                ('hint_usage_rate', models.FloatField(default=0.0)),
                ('avg_focus_score', models.FloatField(blank=True, null=True)),
                ('distraction_rate', models.FloatField(default=0.0)),
                ('pause_frequency', models.FloatField(default=0.0)),
                ('topics_completed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('avg_quiz_score', models.FloatField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_cognitive_load', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'behavior_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('concept_learned', 'Concept Learned'), ('concept_reviewed', 'Concept Reviewed'), ('concept_forgotten', 'Concept Forgotten'), ('error_made', 'Error Made'), ('error_corrected', 'Error Corrected'), ('quiz_completed', 'Quiz Completed'), ('attention_shift', 'Attention Shift'), ('emotion_change', 'Emotion Change'), ('cognitive_overload', 'Cognitive Overload'), ('breakthrough', 'Learning Breakthrough'), ('struggle_detected', 'Struggle Detected')], max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('cognitive_load', models.FloatField(blank=True, null=True)),
                ('emotional_valence', models.FloatField(blank=True, null=True)),
                ('attention_level', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
            ],
            options={
                'db_table': 'cognitive_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knowledge_graph_state', models.JSONField(default=dict)),
                ('knowledge_graph_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=512)),
                ('working_memory_snapshot', models.JSONField(default=dict)),
                ('working_memory_capacity', models.IntegerField(default=7)),
                ('long_term_memory_patterns', models.JSONField(default=dict)),
                ('attention_dynamics', models.JSONField(default=dict)),
                ('attention_history', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('current_emotional_state', models.JSONField(default=dict)),
                ('emotional_history', models.JSONField(default=list)),
                ('current_cognitive_load', models.FloatField(default=0.0)),
                ('cognitive_load_threshold', models.FloatField(default=0.7)),
                ('predicted_performance', models.JSONField(default=dict)),
                ('next_optimal_topics', models.JSONField(default=list)),
                ('predicted_forgetting', models.JSONField(default=dict)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'digital_twins',
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(choices=[('conceptual', 'Conceptual Misunderstanding'), ('procedural', 'Procedural Error'), ('factual', 'Factual Error'), ('careless', 'Careless Mistake'), ('transferal', 'Transfer Error'), ('syntactic', 'Syntax Error'), ('semantic', 'Semantic Error'), ('logical', 'Logical Error')], max_length=50)),
                ('error_subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField()),
                ('error_context', models.JSONField(default=dict)),
                ('correct_solution', models.TextField(blank=True, null=True)),
                ('frequency', models.IntegerField(default=1)),
                ('first_occurrence', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.TextField(blank=True, null=True)),
                ('error_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
            ],
            options={
                'db_table': 'error_patterns',
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_consumed', models.JSONField(default=list)),
                ('focus_score', models.FloatField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('distraction_count', models.IntegerField(default=0)),
                ('pause_count', models.IntegerField(default=0)),
                ('emotional_journey', models.JSONField(default=list)),
                ('avg_cognitive_load', models.FloatField(blank=True, null=True)),
                ('concepts_learned', models.IntegerField(default=0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(blank=True, null=True)),
                ('teaching_actions', models.JSONField(default=list)),
                ('rl_rewards', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'learning_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('quiz_score', 'Quiz Score Prediction'), ('retention', 'Retention Prediction'), ('next_topic', 'Next Topic Recommendation'), ('struggle', 'Struggle Prediction'), ('completion_time', 'Completion Time Prediction'), ('engagement', 'Engagement Prediction')], max_length=50)),
                ('predicted_value', models.JSONField()),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prediction_logs',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('auditory', 'Auditory Learner'), ('kinesthetic', 'Kinesthetic Learner'), ('reading', 'Reading/Writing Learner'), ('multimodal', 'Multimodal Learner')], default='multimodal', max_length=20)),
                ('learning_style_scores', models.JSONField(default=dict)),
                ('preferred_difficulty', models.FloatField(default=0.5)),
                ('learning_speed', models.FloatField(default=1.0)),
                ('attention_span_minutes', models.IntegerField(default=25)),
                ('optimal_session_duration', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('cognitive_style_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=256)),
                ('overall_mastery', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('total_study_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_sessions', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('daily_goal_minutes', models.IntegerField(default=60)),
                ('weekly_goal_topics', models.IntegerField(default=5)),
                ('emotional_baseline', models.JSONField(default=dict)),
                ('stress_tolerance', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_level', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('retention_strength', models.FloatField(default=0.0)),
                ('forgetting_curve_factor', models.FloatField(default=2.0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('activation_count', models.IntegerField(default=0)),
                ('last_activated', models.DateTimeField(blank=True, null=True)),
                ('activation_history', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('misconceptions', models.JSONField(default=list)),
                ('first_encounter', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='students.studentprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='courses.topic')),
            ],
            options={
                'db_table': 'topic_masteries',
            },
        ),
    ]
