# Generated by Django 4.2.27 on 2026-01-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='digital_twin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.digitaltwin'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='topics_covered',
            field=models.ManyToManyField(blank=True, to='courses.topic'),
        ),
        migrations.AddField(
            model_name='errorpattern',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='errorpattern',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='digitaltwin',
            name='current_focus_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.topic'),
        ),
        migrations.AddField(
            model_name='digitaltwin',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='cognitiveevent',
            name='digital_twin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_events', to='students.digitaltwin'),
        ),
        migrations.AddField(
            model_name='cognitiveevent',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.topic'),
        ),
        migrations.AddField(
            model_name='behaviormetrics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('student', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='behaviormetrics',
            unique_together={('student', 'date')},
        ),
    ]
